<a href="https://colab.research.google.com/github/imymemineyay/Studying_NLP/blob/main/wine_recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

과제 1. 코사인 유사도 기반 와인 추천 시스템 개발
- 제공받은 csv 파일 로드
- 상위 5000개의 와인데이터만 추출하여 변수에 저장
- description열 추출
- 불용어 전처리(길이가 짧은 단어, 불용어 사전에 등록되어 있는 단어, 5000개의 문서 중 단어의 등장 횟수가 3개 이하인 경우 제거)
- DTM 구성(만약 시간이 너무 많이 소요되면 상위 1000개만 가지고 하기)
- TFIDF 행렬구성(5000*단어개수)
- 코사인 유사도 (5000*5000)
- ex) 번호가 50번에 해당되는 와인과 가장 유사한 와인을 추천해줘
- 가장 유사한 와인 10개 추천

코사인 유사도 최대값 10개 구해서 그 유사도에 해당하는 와인의 번호 출력

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [ ]:
# 제공받은 csv 파일 로드

df = pd.read_csv('/content/drive/MyDrive/광군제(11.11)/NLP/winemag-data-130k-v2.csv')

In [ ]:
# 상위 5000개의 와인데이터만 추출하여 변수에 저장

wine = df.head(5000)

In [ ]:
# description열 추출

wine = wine.loc[:,['description','title']]
wine.head()

,description,title
0,"Aromas include tropical fruit, broom, brimston...",Nicosia 2013 Vulkà Bianco (Etna)
1,"This is ripe and fruity, a wine that is smooth...",Quinta dos Avidagos 2011 Avidagos Red (Douro)
2,"Tart and snappy, the flavors of lime flesh and...",Rainstorm 2013 Pinot Gris (Willamette Valley)
3,"Pineapple rind, lemon pith and orange blossom ...",St. Julian 2013 Reserve Late Harvest Riesling ...
4,"Much like the regular bottling from 2012, this...",Sweet Cheeks 2012 Vintner's Reserve Wild Child...

In [ ]:
# 불용어 전처리(길이가 짧은 단어, 불용어 사전에 등록되어 있는 단어, 5000개의 문서 중 단어의 등장 횟수가 3개 이하인 경우 제거)

tfidf = TfidfVectorizer(stop_words='english')
wine_m = tfidf.fit_transform(wine['description'])

In [ ]:
count_vt = CountVectorizer(stop_words = 'english')
wine_vt = count_vt.fit_transform(wine['description'])

In [ ]:
wine_vt.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
wine_ct_matrix = np.array(wine_vt.sum(axis=0)[0][0][0])

In [ ]:
max(wine_ct_matrix[0]) # 단어의 가장 높은 빈도수

3063

In [ ]:
len(wine_ct_matrix[0]) # 단어의 총 개수

8179

In [ ]:
# 5000개의 문서 중 단어의 등장 횟수가 3개 이하인 경우 제거
lst = []
for i in range(8179):
    if wine_ct_matrix[0][i] < 4 : # 제거할 열
        lst.append(i)

In [ ]:
wine_pre = wine_m.toarray()
wine_pre = pd.DataFrame(wine_pre)
wine_pre

,0,1,2,3,4,5,6,7,8,9,...,8169,8170,8171,8172,8173,8174,8175,8176,8177,8178
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
saved_lst = []
for i in range(8179):
    if i not in lst:
        saved_lst.append(i)

print(saved_lst)

[0, 4, 5, 7, 10, 11, 12, 13, 15, 17, 18, 20, 23, 25, 29, 38, 64, 66, 67, 68, 69, 70, 72, 74, 76, 77, 79, 81, 82, 83, 84, 85, 86, 87, 88, 91, 92, 93, 94, 95, 96, 97, 98, 100, 103, 109, 110, 111, 112, 114, 116, 119, 122, 124, 128, 130, 133, 135, 136, 139, 142, 143, 145, 148, 150, 153, 156, 158, 164, 166, 169, 173, 178, 182, 183, 185, 187, 189, 198, 200, 210, 211, 213, 214, 216, 217, 219, 221, 226, 227, 229, 230, 244, 245, 246, 247, 251, 253, 260, 264, 265, 267, 268, 269, 271, 272, 276, 279, 295, 301, 313, 316, 317, 318, 319, 321, 322, 324, 325, 326, 329, 330, 335, 342, 344, 346, 348, 354, 357, 362, 364, 365, 368, 372, 373, 375, 376, 377, 379, 383, 384, 387, 389, 395, 396, 397, 399, 400, 401, 405, 407, 408, 412, 414, 420, 433, 434, 435, 443, 455, 459, 461, 462, 463, 464, 465, 467, 468, 471, 472, 474, 475, 482, 484, 485, 486, 490, 491, 492, 494, 495, 499, 507, 509, 515, 521, 522, 523, 525, 526, 527, 543, 546, 550, 551, 552, 553, 560, 571, 572, 575, 578, 581, 586, 587, 598, 601, 602, 604, 612, 613, 623, 628, 632, 639, 640, 641, 642, 643, 648, 650, 653, 657, 658, 659, 660, 661, 662, 667, 668, 669, 671, 677, 681, 682, 683, 684, 687, 689, 692, 694, 696, 700, 701, 703, 706, 707, 709, 710, 712, 721, 726, 727, 728, 729, 733, 735, 736, 737, 745, 746, 750, 751, 755, 759, 760, 762, 764, 769, 771, 775, 783, 785, 790, 796, 797, 798, 799, 801, 802, 805, 808, 809, 812, 813, 823, 824, 826, 827, 829, 830, 831, 832, 833, 836, 838, 841, 842, 844, 851, 852, 853, 854, 859, 860, 861, 862, 863, 867, 870, 871, 872, 874, 875, 877, 878, 879, 881, 885, 889, 890, 896, 899, 904, 906, 910, 912, 919, 923, 926, 936, 940, 941, 942, 943, 944, 945, 952, 953, 959, 961, 963, 968, 971, 977, 980, 981, 992, 995, 997, 998, 1001, 1002, 1011, 1017, 1019, 1021, 1024, 1025, 1026, 1027, 1028, 1031, 1032, 1034, 1035, 1036, 1037, 1038, 1039, 1041, 1044, 1048, 1049, 1054, 1055, 1058, 1059, 1064, 1065, 1073, 1076, 1077, 1078, 1080, 1082, 1084, 1100, 1101, 1103, 1108, 1114, 1116, 1120, 1121, 1122, 1124, 1126, 1130, 1132, 1133, 1134, 1141, 1142, 1144, 1145, 1146, 1150, 1156, 1158, 1159, 1160, 1168, 1181, 1183, 1186, 1192, 1196, 1197, 1201, 1205, 1210, 1213, 1218, 1222, 1230, 1233, 1234, 1238, 1240, 1248, 1255, 1261, 1264, 1266, 1277, 1278, 1279, 1284, 1285, 1291, 1293, 1296, 1304, 1310, 1314, 1316, 1322, 1325, 1327, 1328, 1330, 1332, 1335, 1336, 1339, 1340, 1341, 1344, 1346, 1349, 1354, 1356, 1357, 1360, 1361, 1363, 1370, 1371, 1373, 1374, 1375, 1376, 1378, 1379, 1381, 1383, 1384, 1388, 1394, 1395, 1398, 1405, 1410, 1412, 1416, 1417, 1422, 1425, 1426, 1433, 1434, 1435, 1438, 1443, 1444, 1447, 1448, 1464, 1466, 1467, 1469, 1470, 1471, 1474, 1481, 1484, 1485, 1491, 1492, 1493, 1494, 1500, 1501, 1506, 1508, 1509, 1515, 1523, 1526, 1529, 1531, 1532, 1536, 1538, 1539, 1548, 1549, 1550, 1562, 1570, 1572, 1574, 1575, 1576, 1577, 1578, 1579, 1580, 1584, 1585, 1587, 1588, 1589, 1591, 1597, 1598, 1599, 1601, 1602, 1606, 1608, 1609, 1616, 1619, 1621, 1623, 1632, 1633, 1635, 1637, 1639, 1641, 1642, 1643, 1644, 1645, 1648, 1650, 1653, 1655, 1658, 1660, 1662, 1664, 1669, 1671, 1682, 1684, 1685, 1686, 1687, 1689, 1690, 1691, 1692, 1697, 1698, 1699, 1701, 1704, 1707, 1714, 1715, 1717, 1725, 1726, 1731, 1733, 1734, 1756, 1757, 1761, 1762, 1763, 1767, 1773, 1774, 1777, 1780, 1785, 1787, 1792, 1793, 1795, 1796, 1797, 1798, 1799, 1805, 1810, 1811, 1813, 1814, 1815, 1816, 1817, 1818, 1827, 1837, 1838, 1839, 1847, 1863, 1864, 1865, 1870, 1874, 1875, 1876, 1878, 1885, 1893, 1894, 1898, 1903, 1904, 1909, 1910, 1912, 1914, 1915, 1916, 1917, 1923, 1930, 1932, 1934, 1936, 1937, 1948, 1950, 1955, 1958, 1959, 1961, 1963, 1968, 1975, 1977, 1979, 1981, 1983, 1984, 1988, 1990, 1994, 1998, 2002, 2003, 2004, 2005, 2010, 2011, 2012, 2016, 2021, 2031, 2034, 2035, 2036, 2040, 2043, 2044, 2049, 2050, 2054, 2056, 2061, 2063, 2065, 2066, 2067, 2068, 2069, 2073, 2077, 2078, 2079, 2081, 2082, 2083, 2085, 2086, 2087, 2088, 2089, 2090, 2097, 2098, 2099, 2103, 2104, 2105, 2108, 2109, 2112, 2114, 2115, 2120, 2130, 2131, 2133, 2140, 2157, 2159, 2162, 2163, 2165, 2166, 2167, 2168, 2177, 2178, 2179, 2180, 2181, 2186, 2191, 2195, 2197, 2202, 2204, 2205, 2206, 2207, 2210, 2214, 2219, 2231, 2239, 2240, 2241, 2245, 2247, 2248, 2253, 2254, 2256, 2260, 2265, 2275, 2276, 2281, 2282, 2284, 2286, 2287, 2288, 2289, 2290, 2291, 2300, 2302, 2305, 2307, 2309, 2311, 2318, 2320, 2326, 2328, 2330, 2333, 2334, 2338, 2339, 2341, 2344, 2345, 2348, 2349, 2351, 2352, 2354, 2356, 2360, 2361, 2362, 2364, 2365, 2368, 2371, 2379, 2380, 2382, 2384, 2387, 2391, 2394, 2399, 2401, 2402, 2404, 2405, 2408, 2409, 2411, 2415, 2416, 2428, 2429, 2430, 2432, 2435, 2440, 2442, 2444, 2445, 2447, 2453, 2458, 2459, 2460, 2462, 2463, 2464, 2465, 2466, 2471, 2485, 2486, 2487, 2489, 2490, 2491, 2505, 2507, 2511, 2512, 2513, 2517, 2518, 2520, 2523, 2524, 2525, 2526, 2528, 2534, 2535, 2536, 2550, 2551, 2552, 2553, 2555, 2562, 2572, 2573, 2582, 2583, 2584, 2589, 2590, 2595, 2598, 2599, 2601, 2608, 2609, 2612, 2618, 2619, 2620, 2624, 2628, 2631, 2634, 2636, 2637, 2638, 2639, 2640, 2641, 2644, 2653, 2654, 2657, 2658, 2662, 2663, 2665, 2668, 2669, 2678, 2684, 2685, 2690, 2691, 2693, 2696, 2697, 2698, 2701, 2702, 2703, 2704, 2707, 2709, 2710, 2713, 2714, 2716, 2727, 2731, 2732, 2734, 2736, 2737, 2739, 2742, 2743, 2748, 2751, 2754, 2756, 2757, 2759, 2760, 2761, 2763, 2764, 2766, 2770, 2773, 2775, 2776, 2781, 2782, 2788, 2791, 2793, 2794, 2797, 2798, 2799, 2800, 2802, 2806, 2807, 2809, 2811, 2812, 2818, 2829, 2832, 2834, 2838, 2839, 2843, 2844, 2845, 2848, 2852, 2853, 2854, 2856, 2858, 2861, 2862, 2863, 2864, 2870, 2872, 2874, 2875, 2877, 2880, 2885, 2888, 2893, 2899, 2900, 2903, 2907, 2908, 2909, 2910, 2915, 2917, 2921, 2926, 2928, 2929, 2933, 2934, 2935, 2938, 2940, 2941, 2943, 2944, 2945, 2950, 2953, 2955, 2958, 2959, 2972, 2973, 2974, 2975, 2979, 2980, 2983, 2984, 2988, 2989, 2993, 2995, 2997, 3000, 3004, 3019, 3022, 3024, 3026, 3027, 3034, 3037, 3038, 3039, 3041, 3042, 3043, 3044, 3045, 3046, 3058, 3068, 3069, 3073, 3074, 3075, 3076, 3079, 3081, 3086, 3094, 3095, 3097, 3098, 3099, 3101, 3102, 3106, 3111, 3114, 3116, 3122, 3124, 3132, 3134, 3140, 3142, 3143, 3145, 3150, 3153, 3156, 3157, 3161, 3163, 3181, 3182, 3184, 3186, 3187, 3188, 3189, 3192, 3194, 3197, 3204, 3205, 3206, 3209, 3210, 3215, 3224, 3232, 3233, 3234, 3238, 3242, 3265, 3266, 3267, 3268, 3273, 3275, 3277, 3278, 3281, 3285, 3290, 3292, 3294, 3295, 3297, 3301, 3303, 3304, 3305, 3306, 3309, 3311, 3312, 3315, 3316, 3321, 3325, 3326, 3328, 3331, 3335, 3337, 3339, 3340, 3348, 3353, 3355, 3359, 3360, 3363, 3365, 3366, 3369, 3370, 3376, 3378, 3379, 3380, 3383, 3386, 3387, 3388, 3389, 3392, 3394, 3395, 3396, 3397, 3400, 3404, 3410, 3417, 3427, 3428, 3430, 3434, 3437, 3440, 3441, 3447, 3459, 3460, 3462, 3466, 3468, 3470, 3472, 3473, 3482, 3485, 3486, 3487, 3488, 3491, 3494, 3496, 3498, 3499, 3505, 3506, 3508, 3512, 3514, 3515, 3517, 3522, 3525, 3529, 3533, 3534, 3535, 3537, 3542, 3552, 3553, 3555, 3556, 3557, 3558, 3559, 3562, 3564, 3565, 3567, 3568, 3572, 3573, 3574, 3576, 3579, 3580, 3586, 3587, 3589, 3591, 3593, 3597, 3599, 3600, 3602, 3603, 3605, 3614, 3620, 3625, 3626, 3627, 3631, 3632, 3633, 3634, 3636, 3637, 3647, 3650, 3652, 3653, 3660, 3673, 3674, 3675, 3677, 3682, 3683, 3684, 3692, 3693, 3694, 3699, 3701, 3702, 3703, 3705, 3708, 3709, 3710, 3712, 3713, 3714, 3723, 3729, 3731, 3737, 3746, 3749, 3750, 3752, 3755, 3760, 3761, 3762, 3764, 3776, 3780, 3784, 3785, 3788, 3790, 3791, 3792, 3793, 3796, 3799, 3803, 3807, 3811, 3817, 3819, 3820, 3822, 3825, 3832, 3835, 3836, 3840, 3841, 3842, 3848, 3849, 3856, 3859, 3868, 3870, 3871, 3876, 3883, 3891, 3893, 3901, 3904, 3906, 3907, 3920, 3921, 3923, 3926, 3927, 3931, 3935, 3936, 3937, 3947, 3959, 3960, 3964, 3965, 3969, 3970, 3974, 3975, 3976, 3977, 3978, 3979, 3982, 3983, 3985, 3989, 3994, 3995, 4004, 4005, 4006, 4009, 4011, 4012, 4014, 4015, 4018, 4027, 4030, 4041, 4046, 4051, 4052, 4053, 4056, 4057, 4059, 4061, 4063, 4065, 4066, 4067, 4073, 4074, 4080, 4081, 4082, 4083, 4088, 4090, 4091, 4094, 4095, 4096, 4098, 4099, 4101, 4102, 4105, 4106, 4108, 4110, 4111, 4113, 4114, 4115, 4117, 4118, 4119, 4124, 4126, 4130, 4132, 4133, 4134, 4135, 4136, 4137, 4139, 4141, 4143, 4146, 4148, 4150, 4156, 4157, 4158, 4159, 4161, 4166, 4167, 4168, 4169, 4170, 4172, 4173, 4174, 4175, 4176, 4177, 4178, 4180, 4183, 4186, 4190, 4191, 4194, 4199, 4201, 4203, 4204, 4206, 4207, 4208, 4213, 4216, 4218, 4221, 4227, 4229, 4234, 4236, 4237, 4241, 4242, 4243, 4244, 4246, 4247, 4256, 4257, 4261, 4262, 4263, 4264, 4265, 4269, 4270, 4271, 4272, 4273, 4274, 4275, 4276, 4281, 4282, 4283, 4284, 4285, 4294, 4297, 4299, 4300, 4302, 4305, 4309, 4312, 4313, 4315, 4339, 4348, 4349, 4350, 4352, 4353, 4356, 4357, 4358, 4359, 4361, 4363, 4366, 4367, 4375, 4377, 4381, 4393, 4396, 4401, 4403, 4410, 4412, 4413, 4414, 4415, 4418, 4419, 4420, 4424, 4427, 4429, 4431, 4437, 4438, 4439, 4448, 4449, 4457, 4458, 4459, 4461, 4466, 4468, 4469, 4470, 4479, 4488, 4489, 4490, 4495, 4496, 4497, 4499, 4500, 4501, 4504, 4505, 4506, 4508, 4510, 4511, 4514, 4516, 4518, 4524, 4526, 4529, 4530, 4531, 4533, 4536, 4544, 4550, 4556, 4560, 4571, 4573, 4574, 4578, 4581, 4588, 4589, 4593, 4600, 4602, 4605, 4612, 4613, 4614, 4615, 4616, 4618, 4625, 4627, 4630, 4637, 4638, 4640, 4646, 4647, 4648, 4650, 4653, 4658, 4659, 4660, 4661, 4664, 4665, 4669, 4672, 4677, 4688, 4694, 4707, 4718, 4724, 4732, 4733, 4735, 4737, 4739, 4741, 4742, 4743, 4746, 4748, 4751, 4754, 4758, 4760, 4766, 4768, 4770, 4772, 4773, 4774, 4776, 4777, 4778, 4786, 4792, 4800, 4805, 4811, 4813, 4814, 4821, 4822, 4824, 4826, 4829, 4830, 4831, 4835, 4838, 4839, 4840, 4841, 4842, 4843, 4856, 4857, 4859, 4860, 4862, 4864, 4865, 4867, 4874, 4875, 4881, 4891, 4894, 4895, 4897, 4898, 4899, 4904, 4905, 4906, 4907, 4910, 4911, 4913, 4914, 4917, 4920, 4926, 4927, 4928, 4932, 4934, 4935, 4936, 4938, 4939, 4944, 4945, 4950, 4957, 4958, 4965, 4966, 4970, 4972, 4974, 4977, 4983, 4985, 4989, 4990, 4991, 4993, 4994, 4999, 5003, 5007, 5008, 5009, 5011, 5014, 5020, 5021, 5022, 5023, 5024, 5025, 5030, 5031, 5032, 5033, 5034, 5051, 5053, 5058, 5063, 5071, 5075, 5080, 5085, 5087, 5088, 5090, 5092, 5096, 5097, 5098, 5100, 5102, 5103, 5105, 5107, 5112, 5115, 5116, 5124, 5125, 5126, 5131, 5134, 5148, 5163, 5164, 5171, 5172, 5173, 5175, 5176, 5177, 5180, 5181, 5184, 5186, 5188, 5190, 5191, 5193, 5194, 5203, 5215, 5216, 5217, 5218, 5219, 5222, 5224, 5225, 5237, 5239, 5246, 5248, 5249, 5254, 5256, 5257, 5259, 5261, 5264, 5268, 5276, 5279, 5284, 5285, 5286, 5287, 5292, 5299, 5300, 5301, 5303, 5304, 5306, 5313, 5315, 5317, 5318, 5320, 5339, 5342, 5343, 5346, 5347, 5354, 5358, 5360, 5362, 5363, 5365, 5366, 5367, 5368, 5370, 5372, 5373, 5376, 5383, 5384, 5386, 5391, 5393, 5396, 5399, 5402, 5411, 5412, 5414, 5417, 5419, 5422, 5423, 5424, 5425, 5428, 5431, 5433, 5434, 5440, 5443, 5444, 5446, 5447, 5448, 5458, 5460, 5461, 5465, 5471, 5472, 5473, 5475, 5476, 5480, 5483, 5484, 5486, 5489, 5493, 5494, 5500, 5508, 5510, 5511, 5516, 5517, 5519, 5522, 5524, 5525, 5529, 5530, 5532, 5533, 5534, 5535, 5536, 5540, 5544, 5548, 5550, 5554, 5559, 5565, 5566, 5568, 5570, 5573, 5574, 5577, 5583, 5587, 5589, 5590, 5593, 5596, 5600, 5601, 5602, 5611, 5613, 5617, 5623, 5624, 5625, 5626, 5627, 5628, 5629, 5630, 5631, 5640, 5643, 5644, 5645, 5647, 5648, 5650, 5656, 5657, 5660, 5666, 5674, 5678, 5679, 5680, 5682, 5683, 5684, 5688, 5690, 5696, 5704, 5705, 5706, 5707, 5709, 5712, 5714, 5717, 5718, 5720, 5722, 5724, 5726, 5727, 5728, 5732, 5734, 5735, 5736, 5737, 5739, 5741, 5742, 5749, 5750, 5754, 5755, 5757, 5761, 5762, 5765, 5766, 5767, 5770, 5772, 5776, 5784, 5786, 5795, 5799, 5801, 5804, 5809, 5816, 5820, 5821, 5823, 5831, 5832, 5835, 5836, 5837, 5840, 5843, 5845, 5848, 5853, 5854, 5856, 5857, 5858, 5861, 5869, 5875, 5876, 5878, 5879, 5880, 5884, 5888, 5889, 5892, 5895, 5898, 5899, 5902, 5904, 5907, 5914, 5918, 5919, 5927, 5930, 5931, 5932, 5933, 5935, 5943, 5946, 5964, 5978, 5979, 5980, 5981, 5982, 5983, 5986, 5993, 5994, 5998, 6000, 6003, 6005, 6006, 6009, 6010, 6014, 6016, 6018, 6019, 6022, 6027, 6036, 6037, 6044, 6045, 6046, 6048, 6049, 6050, 6051, 6054, 6055, 6056, 6059, 6060, 6061, 6064, 6065, 6066, 6070, 6074, 6075, 6076, 6078, 6079, 6080, 6082, 6087, 6088, 6089, 6091, 6095, 6104, 6107, 6108, 6111, 6112, 6116, 6118, 6119, 6122, 6124, 6128, 6137, 6139, 6141, 6142, 6145, 6146, 6148, 6150, 6151, 6153, 6155, 6156, 6162, 6164, 6167, 6168, 6170, 6172, 6173, 6174, 6177, 6178, 6181, 6187, 6190, 6191, 6194, 6196, 6199, 6201, 6205, 6218, 6219, 6220, 6221, 6222, 6223, 6225, 6228, 6229, 6234, 6235, 6238, 6241, 6243, 6244, 6246, 6250, 6253, 6254, 6256, 6260, 6263, 6264, 6268, 6269, 6278, 6283, 6284, 6286, 6288, 6289, 6291, 6295, 6297, 6304, 6305, 6306, 6307, 6309, 6313, 6315, 6319, 6323, 6324, 6325, 6329, 6338, 6340, 6346, 6353, 6360, 6362, 6366, 6368, 6373, 6374, 6381, 6387, 6388, 6396, 6404, 6405, 6407, 6409, 6412, 6420, 6423, 6426, 6428, 6429, 6430, 6432, 6439, 6440, 6446, 6447, 6448, 6452, 6454, 6456, 6458, 6460, 6461, 6464, 6465, 6466, 6469, 6470, 6473, 6482, 6483, 6486, 6488, 6489, 6492, 6499, 6505, 6510, 6515, 6516, 6518, 6520, 6528, 6534, 6538, 6540, 6544, 6546, 6558, 6560, 6561, 6562, 6567, 6571, 6572, 6574, 6575, 6576, 6579, 6584, 6589, 6593, 6597, 6598, 6600, 6601, 6603, 6604, 6605, 6606, 6608, 6612, 6613, 6614, 6619, 6621, 6623, 6627, 6632, 6633, 6634, 6640, 6643, 6645, 6651, 6655, 6656, 6657, 6661, 6666, 6668, 6669, 6671, 6672, 6676, 6679, 6680, 6681, 6684, 6685, 6686, 6688, 6689, 6691, 6692, 6695, 6696, 6700, 6701, 6710, 6713, 6716, 6719, 6720, 6721, 6722, 6724, 6725, 6726, 6727, 6728, 6729, 6733, 6735, 6739, 6741, 6742, 6743, 6744, 6745, 6746, 6747, 6748, 6749, 6753, 6758, 6759, 6760, 6761, 6762, 6763, 6767, 6768, 6773, 6774, 6778, 6780, 6787, 6789, 6794, 6796, 6798, 6799, 6810, 6813, 6815, 6816, 6817, 6819, 6821, 6829, 6832, 6841, 6846, 6850, 6852, 6858, 6861, 6863, 6864, 6868, 6869, 6873, 6878, 6881, 6883, 6886, 6890, 6892, 6893, 6896, 6897, 6898, 6902, 6903, 6906, 6908, 6910, 6912, 6915, 6917, 6922, 6923, 6924, 6926, 6928, 6930, 6939, 6941, 6943, 6949, 6950, 6951, 6952, 6953, 6956, 6957, 6958, 6967, 6970, 6971, 6974, 6977, 6984, 6986, 6987, 6989, 6995, 6996, 6997, 6999, 7000, 7001, 7002, 7006, 7010, 7013, 7017, 7019, 7020, 7021, 7023, 7024, 7034, 7036, 7037, 7039, 7041, 7042, 7043, 7045, 7052, 7058, 7059, 7063, 7064, 7065, 7068, 7069, 7070, 7074, 7082, 7086, 7087, 7088, 7089, 7090, 7092, 7093, 7099, 7104, 7106, 7111, 7114, 7118, 7119, 7120, 7121, 7127, 7131, 7133, 7136, 7137, 7139, 7140, 7145, 7146, 7147, 7149, 7152, 7153, 7154, 7156, 7157, 7163, 7173, 7174, 7177, 7179, 7184, 7185, 7187, 7191, 7199, 7200, 7201, 7202, 7206, 7209, 7217, 7224, 7225, 7226, 7234, 7236, 7237, 7238, 7239, 7241, 7243, 7245, 7248, 7255, 7256, 7257, 7258, 7259, 7260, 7262, 7265, 7266, 7269, 7270, 7272, 7276, 7278, 7281, 7283, 7287, 7294, 7300, 7302, 7304, 7306, 7312, 7314, 7316, 7319, 7320, 7321, 7326, 7327, 7328, 7329, 7331, 7337, 7338, 7339, 7340, 7341, 7345, 7347, 7349, 7354, 7355, 7357, 7358, 7359, 7366, 7373, 7374, 7375, 7387, 7389, 7392, 7394, 7398, 7399, 7402, 7406, 7407, 7412, 7413, 7414, 7423, 7427, 7428, 7430, 7431, 7432, 7433, 7434, 7437, 7438, 7444, 7450, 7451, 7452, 7453, 7454, 7455, 7458, 7470, 7471, 7472, 7473, 7474, 7477, 7478, 7479, 7480, 7481, 7486, 7487, 7489, 7510, 7511, 7512, 7516, 7536, 7544, 7545, 7548, 7550, 7551, 7569, 7570, 7571, 7572, 7574, 7576, 7578, 7580, 7581, 7582, 7588, 7589, 7591, 7592, 7595, 7597, 7602, 7610, 7619, 7621, 7631, 7632, 7633, 7636, 7640, 7644, 7647, 7648, 7653, 7663, 7664, 7675, 7680, 7684, 7686, 7694, 7696, 7700, 7701, 7706, 7711, 7724, 7725, 7729, 7730, 7731, 7746, 7748, 7749, 7751, 7753, 7761, 7762, 7764, 7765, 7766, 7772, 7773, 7775, 7776, 7777, 7778, 7779, 7780, 7785, 7789, 7792, 7793, 7801, 7802, 7805, 7806, 7810, 7813, 7816, 7818, 7824, 7828, 7829, 7850, 7855, 7856, 7857, 7858, 7859, 7860, 7864, 7865, 7866, 7868, 7870, 7871, 7880, 7887, 7891, 7899, 7900, 7901, 7905, 7907, 7919, 7920, 7921, 7923, 7924, 7929, 7930, 7933, 7937, 7939, 7940, 7942, 7946, 7949, 7952, 7954, 7955, 7959, 7960, 7961, 7963, 7964, 7965, 7966, 7970, 7973, 7975, 7982, 7987, 7990, 7994, 7995, 8003, 8006, 8010, 8011, 8014, 8017, 8018, 8024, 8025, 8028, 8031, 8040, 8043, 8045, 8047, 8048, 8049, 8050, 8054, 8059, 8069, 8071, 8072, 8075, 8077, 8080, 8081, 8082, 8083, 8086, 8087, 8088, 8089, 8098, 8100, 8102, 8103, 8104, 8107, 8108, 8109, 8110, 8120, 8127, 8128, 8129, 8130, 8132, 8133, 8135, 8136, 8137, 8145, 8148, 8149, 8150, 8160, 8162, 8163, 8165, 8166, 8168, 8169, 8171, 8173, 8176]

In [ ]:
wine_pre = wine_pre.iloc[:,saved_lst]
wine_pre

,0,4,5,7,10,11,12,13,15,17,...,8160,8162,8163,8165,8166,8168,8169,8171,8173,8176
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.166211,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
tfidf_m = wine_pre.values # df → array 변환
tfidf_m

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
cos_sim = cosine_similarity(tfidf_m,tfidf_m)
print(cos_sim.shape)
print(cos_sim[0])

(5000, 5000)
[1.         0.0150337  0.01370403 ... 0.00910957 0.         0.03358695]

In [ ]:
wine.title

0                       Nicosia 2013 Vulkà Bianco  (Etna)
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)
2           Rainstorm 2013 Pinot Gris (Willamette Valley)
3       St. Julian 2013 Reserve Late Harvest Riesling ...
4       Sweet Cheeks 2012 Vintner's Reserve Wild Child...
                              ...
4995    Mud House 2007 Swan Sauvignon Blanc (Marlborough)
4996     Fattoria Alois 2006 Cunto Pallagrello (Campania)
4997                      Florio NV Fine Sweet  (Marsala)
4998    Vice Versa 2005 Le Petit Vice Cabernet Sauvign...
4999    Viña Mar de Casablanca 2008 Reserva Especial S...
Name: title, Length: 5000, dtype: object

In [ ]:
wine.iloc[516]

description    This is a relatively thick and dense wine, gri...
title          Davis Family 2014 Soul Patch Estate Grown Pino...
Name: 516, dtype: object

In [ ]:
i = wine.iloc[49,1]
print(i)

Vignerons de Bel Air 2011 Eté Indien  (Brouilly)

In [ ]:
def recommend(t, cosine_sim = cos_sim): # t에 제목 전달
  idx = data[t]
  #print(cosine_sim[idx])
  sim_scores = list(enumerate(cosine_sim[idx]))
  # print(sim_scores)
  ss = sorted(sim_scores, key = lambda x:x[1], reverse=True)
  #print(ss)
  ss = ss[1:11]
  print(ss)


  res = [i[0] for i in ss]
  print(res)
  return wine['title'].iloc[res]

In [ ]:
recommend('Vignerons de Bel Air 2011 Eté Indien  (Brouilly)')

[(30, 0.4728694130117888), (4091, 0.4622114339243789), (2396, 0.42736711962396173), (4561, 0.4049711854885382), (1552, 0.4011213804846594), (3602, 0.4004374765517892), (4563, 0.395994292202158), (4397, 0.39463986866359063), (3400, 0.3935506078939345), (2657, 0.37909491996976724)]
[30, 4091, 2396, 4561, 1552, 3602, 4563, 4397, 3400, 2657]

30      Domaine de la Madone 2012 Nouveau  (Beaujolais...
4091     Casca Wines 2013 Santos da Casa Red (Alentejano)
2396    Rui Roboredo Madeira 2015 Beyra Colheita Red (...
4561    Jose Maria Vieira 2014 Borges Quinta da Soalhe...
1552    Adega Cooperativa de Borba 2016 Cuvée B Red (A...
3602                    La Croix de Renaud 2009  Bordeaux
4563    Les Vignerons Réunis de Monségur 2014 Château ...
4397    Georges Duboeuf 2015 Clos Reyssie  (Pouilly-Fu...
3400    Parras Vinhos 2014 Montaria Tinto Red (Alentej...
2657                  Château Soutard 2009  Saint-Émilion
Name: title, dtype: object